# This will create a Docker Manager Node
AWSTemplateFormatVersion: "2010-09-09"

Description: "Docker Manager Node"

Parameters:
  MgrENI:
    Description: Static private IP address for Mgr Node
    Type: String
  EnvironmentName:
    Description: Environment Name for tags
    Type: String


Resources:
  ClusterJoinCmd:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: "Param to store command to join worker node to Docker Swarm"
      Name: ClusterJoinCmd
      Tier: Standard
      Type: String
      Value: "Temp value because null not accepted"
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-SwarmJoinCmd

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MgrENI
          DeviceIndex: 0
      IamInstanceProfile:
        !Ref MyProfile
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum -y update;
            yum install -y docker jq;
            systemctl start docker;
            usermod -aG docker ec2-user;
            echo $(docker swarm init --advertise-addr 172.31.32.20) >> /tmp/dockerjoin.txt;
            cat /tmp/dockerjoin.txt | sed 's/.*command: //' | sed 's/ To add.*$//' >> /tmp/join.txt;
            aws ssm put-parameter --name /ClusterJoinCmd --value "$(cat /tmp/join.txt)" --type String --region eu-west-2 --overwrite;
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-SwarmMgr

  MgrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-SSM-Params-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for EC2 to read/write SSM Parameters via CLI
      MaxSessionDuration: 3600 # Role active for 1 hour
      Path: /
      Policies: 
        - PolicyName: EC2-SSM-Params-Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:AddTagsToResource
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:RemoveTagsFromResource
                Resource: arn:aws:ssm:*:*:parameter/*
      Tags: 
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-TempSSMRole
  
  MyProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: Access-SSM-Params-Profile
      Path: /
      Roles: 
        - EC2-SSM-Params-Role
